### ISSUE TITLE
Can't get it working

### ISSUE THREAD

**Issue by MWEJ** [btoddb/flume-ng-cassandra-sink#1]
Hi

I can't get the flume sink working. I keep getting the error "Missing flume header attribute, 'key' - cannot process this event" when I try to stream a file using the avro-client. I'm using this command:

bin/flume-ng avro-client --conf conf -H localhost -p 4141 -F /var/log/boot.log

Any idea what I'm doing wrong?

**Comment by btoddb** [comment]
sorry took so long to get back to you, but the key is a unique key within
"src" for storing the log data in cassandra.  so the cassandra key is "src
- key"

**Comment by btoddb** [comment]
i've updated README.  take another look to see if you can make it work

**Comment by nirmoy** [comment]
How can i add flume event header "key".  I use org.apache.flume.interceptor.StaticInterceptor$Builder but didn't help as it add same key for  all events so it replace previous event in cassandra . How can I add event header "key" on fly according to the flume body?? I've try org.apache.flume.interceptor.RegexFilteringInterceptor$Builder too but unable to make it work.

**Comment by btoddb** [comment]
a client should add the "key" header to the flume event.  your client is
talking to a source, right.  the client can put whatever headers it wants
on the FlumeEvent, in particular it must add the "key" header.  then it
sends the event to the source.  the source puts it in the channel,
cassandra sink reads events from the channel and can read the "key" header

**Comment by Deepak-Vohra** [comment]
The required headers get added using the static, org.apache.flume.interceptor.TimestampInterceptor$Builder and org.apache.flume.interceptor.HostInterceptor$Builder interceptors, but the data streamed to Cassandra is encoded, the following gets listed in Cassandra Client shell.

[default@flume] list wlslog;
Using default limit of 100
Using default cell limit of 100
RowKey: mysql:dc1
=> (name=data, value=392c4170722d382d323031342d373a30363a32342d504d2d5044542c4e6f746963652c5765624c6f6769635365727665722c41646d696e5365727665722c4245412d3030303336302c536572766572207374617274656420696e2052554e4e494e47206d6f6465, timestamp=1424117969008015)
=> (name=host, value=6c6f63616c686f7374, timestamp=1424117969008014)
=> (name=src, value=6d7973716c, timestamp=1424117969008013)
=> (name=ts, value=323031352d30322d31365432303a31393a32322e3530315a, timestamp=1424117969008012)
