### ISSUE TITLE
Event retries in flume sink?

### ISSUE THREAD

**Issue by utsengar** [btoddb/flume-ng-cassandra-sink#5]
The hbase sink says: " In the event of Hbase failing to write certain events, the sink will replay all events in that transaction.": http://flume.apache.org/FlumeUserGuide.html

So I wanted to know how is this implemented in flume-ng-cassandra? Is this a sync or an async client? 

Can you please point me to the class which will handle (and retry) a connection time out error like this:

```
me.prettyprint.hector.api.exceptions.HectorTransportException: org.apache.thrift.transport.TTransportException: java.net.SocketTimeoutException: Read timed out
```

Thanks,
-Utkarsh

**Comment by btoddb** [comment]
hector handles that internally.  if the sink gets an error from hector, the
command has already been retried

**Comment by utsengar** [comment]
Thanks for the update! 

What I am noticing in my flume-ng cassandra instance is, cassandra throws a `SocketTimeoutException` and the data is not persisted (and as you said, hector should have tried a retry). So, in that case HectorException should be called here: `CassandraSink:176`? 
Infact I have logger in all the catch() blocks and none of the catch blocks are catching an exception but data is not persisted (I am still testing ChannelException).

Also, you have `transaction.rollback();` in your catch blocks. That means it will be retried again right?

**Comment by btoddb** [comment]
because of the way the CassandraSinkRepository tries to batch mutator
"executes" the exception is being caught in the CassandraWriteWork class.
 this is one of the last things i worked on, and it oviously needs a little
more work.

probably what needs to be done is pass the exception somehow
through CassandraWorkStatus callback to notify CassandraJob, which could
then either log the exception or rethrow so CassandraSink can get it.  does
that make sense?

care to take a stab at fixing it for us :)

**Comment by utsengar** [comment]
That helps! 

And sure, I will try to submit fix for this.
I am running a fairly modified version of flume-ng-cassandra-sink, but I can surely try it out!

**Comment by btoddb** [comment]
if there is anything else you would like to contribute from your work, send
a pull request and i will happily take a look at it.

thx for trying it out and giving feedback!

**Comment by sgsits** [comment]
Hi btoddb & utkarsh2012,

Firstly kudos to btoddb for the cassandra sink, secondly thanks to utkarsh2012 for bringing up this issue.
I also faced this issue sometime back and was able to find a solution for the same.
I am going to send a pull request having a Fix for this in next couple of minutes.

**Comment by btoddb** [comment]
pushed a fix for this out.  i didn't have time to write the unit test cuz it requires some retooling .. give it a go and lemme know!

**Comment by utsengar** [comment]
Thanks! I will try this out.

Also, I have a question about the way this library handles counter increments. I batch counters and do a `mutator.execute()` frequently. Everything works fine when there are no TimeoutExceptions. But when cassandra throws SocketTimeoutExceptions to hector. I see that the counter values are doubled or also tripled at times.

I am not sure about this bug, this can also be a bug on my side but I am just trying to understand how retries for counters is handles in hector (or this library).
My keyspace config: `keyspace = HFactory.createKeyspace(keyspaceName, cluster, CONSISTENCY_LEVEL_POLICY, FailoverPolicy.ON_FAIL_TRY_ALL_AVAILABLE, credentials);`

And I call this multiple times before calling `mutator.execute()`:

`mutator.addCounter(ByteBuffer.wrap(eventType.getBytes()), "xxx", HFactory.createCounterColumn( Helper.getRoundedTime(timestamp, 60), count, LongSerializer.get() ));`

Any suggestions?
